# test config mushra page, 2 trials: 1) not randomized, condition names shown 2) 

testname: Spatial Characteristics Test
testId: bbcspatial
bufferSize: 2048
stopOnErrors: false
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: intro
      name: Introduction
      content: <p>Welcome to my spatial characteristics test.</p><p>I've built an interface for rating spatial characteristics.</p>
    - type: bbc_spatial
      id: trial1
      name: Castanets (15˚,-15˚)
      content: Please compare the test condition to the reference and indicate the perceived spatial characteristics of the test condition.<br/>Use the scale on the left-hand-side to indicate the height relative to the reference.<br/>Use the radar display on the right-hand-side to indicate the azimuth direction, distance, and width of test condition.
      showConditionNames: false
      showWaveform: true
      enableLooping: false
      referenceParams:
        azimuth: 15
        elevation: -15
      reference: configs/resources/decorr/castanets_extent_az15_el-15_diff0_w0h0/bear_decorr_none_point.wav
      stimuli: 
          Rand512: configs/resources/decorr/castanets_extent_az15_el-15_diff1_w30h15/bear_decorr_randphase512.wav
          Rand256: configs/resources/decorr/castanets_extent_az15_el-15_diff1_w30h15/bear_decorr_randphase256.wav
          Exp8ms: configs/resources/decorr/castanets_extent_az15_el-15_diff1_w30h15/bear_decorr_exp8ms.wav
      mustRate: true
    - type: likert_comparison
      id: likert_1
      name: Castanets (15˚,-15˚)
      content: Please compare the test condition to the reference and indicate the timbral quality of the test condition with respect to the reference.<br/>Timbral quality is the degree of similarity or difference in the character of the test condition compared to the reference, for all characteristics that are not related to spatial characteristics, pitch, or loudness.<br/>If the timbre of the test condition is very close to that of the reference, it should be marked as Very Good.
      showConditionNames: false
      showWaveform: true
      enableLooping: false
      reference: configs/resources/decorr/castanets_extent_az15_el-15_diff0_w0h0/bear_decorr_none_point.wav
      stimuli: 
          Rand512: configs/resources/decorr/castanets_extent_az15_el-15_diff1_w30h15/bear_decorr_randphase512.wav
          Rand256: configs/resources/decorr/castanets_extent_az15_el-15_diff1_w30h15/bear_decorr_randphase256.wav
          Exp8ms: configs/resources/decorr/castanets_extent_az15_el-15_diff1_w30h15/bear_decorr_exp8ms.wav
      mustPlayback: true
      response:
        - value: very bad
          label: Very Bad
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: bad
          label: Bad
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: fair
          label: Fair
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: good
          label: Good
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png 
        - value: very good
          label: Very Good
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png 
      mustRate: true
    - type: finish
      name: Thank you
      content: Thank you for your time and effort.
      popupcontent: Your results were sent. Goodbye and have a nice day      
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other