# Likert single stimulus page 1 stimuli, 5 responses


testname: Overall Listening Experience - Single Stimuli Rating
testId: ole_cata
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php



pages:

    - type: OLE_CATA
      id: first_page
      name: Stimuli 1
      content: How much do you enjoy listening to the following music item?
      mustRate: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
      response:
        - value: not at all
          label: Not at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: not a lot
          label: Not a lot
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: neutral
          label: Neutral
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: quite
          label: Quite
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png   
        - value: a lot
          label: A lot
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png 
      questionnaire:
        - type: attributeheading
          label: Attribute selection
          content: Please select all attributes which contributes most to your listening experience rating
        - type: checkboxes
          label: Spatial   
          name: spatial
          response:
            - value: enveloping
              label: Enveloping
              popUp: definition of enveloping
            - value: sounds easily localized
              label: Sounds easily localized
              popUp: definition of sounds easily localized
            - value: sounds hard to localise
              label: Sounds hard to localise
              popUp: definition of sounds hard to localise
        - type: checkboxes
          label: Timbral   
          name: timbral
          response:
            - value: strong colouration
              label: Strong colouration
              popUp: definition of strong colouration
            - value: subtle colouration
              label: Subtle colouration
              popUp: definition of subtle colouration
            - value: no colouration
              label: No colouration
              popUp: definition of no colouration
            - value: phasiness comb-filtering
              label: Phasiness / comb-filtering
              popUp: definition of phasiness comb-filtering
        - type: checkboxes
          label: Head movement   
          name: head movement
          response:
            - value: obvious latency
              label: Obvious latency
              popUp: definition of obvious latency
            - value: subtle latency
              label: Subtle latency
              popUp: definition of subtle latency
            - value: no latency
              label: No latency
              popUp: definition of no latency
            - value: localisation stable with head movement
              label: Localisation stable with head movement
              popUp: definition of localization stable with head movement
            - value: localisation unstable with head movement
              label: Localisation unstable with head movement
              popUp: definition of localization unstable with head movement
        - type: checkboxes
          label: Dynamics  
          name: dynamics 
          response:
            - value: louder
              label: Louder
              popUp: definition of louder
            - value: quieter
              label: Quieter
              popUp: definition of quieter
            - value: reduced dynamic range
              label: Reduced dynamic range
              popUp: definition of reduced dynamic range
            - value: increased dynamic range
              label: Increased dynamic range
              popUp: definition of increased dynamic range
        - type: checkboxes
          label: General  
          name: general
          response:
            - value: clear
              label: Clear
              popUp: definition of clear
            - value: unclear
              label: Unclear 
              popUp: definition of unclear
            - value: natural
              label: Natural
              popUp: definition of natural
            - value: unnatural
              label: Unnatural
              popUp: definition of unnatural
            - value: immersive
              label: Immersive
              popUp: definition of immersive
        - type: notesheading
          label: Extra notes
          content: Give any further explanation for your ratings
        - type: long_text
          name: Extra notes
          optional: true
      
    - type: OLE_CATA
      id: second_page
      name: Stimuli 2
      content: How much do you enjoy listening to the following music item?
      mustRate: true
      stimuli:
          C2: configs/resources/audio/mono_c2.wav
      response:
        - value: not at all
          label: Not at all
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: not a lot
          label: Not a lot
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: neutral
          label: Neutral
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png
        - value: quite
          label: Quite
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png   
        - value: a lot
          label: A lot
          img: configs/resources/images/star_off.png
          imgSelected: configs/resources/images/star_on.png
          imgHigherResponseSelected: configs/resources/images/star_on.png

    - type: finish
      name: Thank you
      content: Thank you for attending
      showResults: true
      writeResults: true
